### ISSUE TITLE
update Data Licensensing Guide

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/academy#140]
The tutorial https://openenergy-platform.org/tutorials/jupyter/tutorial_open-data-licenses/ needs an update:

- The title needs a correction: Licensensing  --> Licensing 
- Remove all the ¶
- Introduction: Add few words about why licensing (at all) is important: e.g. reference the sentences from below. For example: _Licensing your data is important because is provides a legal certainty for its further usage. Also, in some countries, like Germany, it is not possible to waive one's copyright. Data that don't come with any license are not open!_
- Section "Open Licenses": maybe specify "the four freedoms" in the text or remove the link from "free software" to "the four freedoms". Alro: remove the right parenthesis at the end of the section.
- Section "Licenses which are not open": Remove one "that" from the first sentence.
- Section "Public Domain": 
   - "unrestricted" instead if "unrestructed"? 
   - The usecase sentence is bad English... better: Usecase: Data for which no attribution to authors is required, e.g. "helper tables" for conversions.
   - table: ids are shifted, this is confusing...
- Section "Attribution": same as the usecase sentence in "Public Domain", ids in the table are also shifted here
- Section "Share-Alike": first sentence better: 
   - "...requires that you choose..."
   - same for usecases, see above
- maybe add ablank line between the subsections of "Open Data Licenses"
- bottom: There is smth missing "In [ ]:" 

This is important for the PtJ link list!

**Comment by christian-rli** [comment]
I agree that all these ¶ symbols look bad. They do have a function, however. They allow linking to subsections of the document. In my opinion these should be replaced with a less intrusive symbol, like # or most appropriately: 🔗 There are a range of displaying issues for jupyter notebooks that should be addressed. For this particular problem I'm creating the issue #141 .

I am not sure what ou mean by shifted ids. Is this "just" a displaying error?

I addressed all other points.
