### ISSUE TITLE
Correct spelling mistake in API Tutorial 1 title

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/academy#145]
There is a spelling mistake in the title: Introduction to the OEP-API and basic table opperations
Todo: change to: Introduction to the OEP-API and basic table operations

https://openenergy-platform.org/tutorials/jupyter/OEP_API_tutorial_part1/

**Comment by han-f** [comment]
any news on this?

**Comment by jh-RLI** [comment]
No progress yet, my priorities are on other tasks. I will try to fix this as soon as possible (at least within the next 2 weeks).

**Comment by han-f** [comment]
closing as tutorials are now on OEA and rearranged.
