### ISSUE TITLE
Link to outdated readthedocs in some tutorials

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/academy#150]
Some tutorials, for example this: https://openenergy-platform.org/tutorials/jupyter/OEP_API_tutorial_part1/
have links to readthedocs: https://oep-data-interface.readthedocs.io/en/latest/api/how_to.html

Currently this text there is outdated which may be frustrating to users that search for an up-to-date API documentation. What could be a solution for the time being until there is a proper and up-to-date documentation?

cc @wingechr

**Comment by wingechr** [comment]
#153 
* i removed references to the readthedoc (`oep-data-interface.readthedocs.io`)
* i also changed references from `oep.iks.cs.ovgu.de` to ``openenergy-platform.org`

# TODO: the markdown tutorials can only be fixed manually on the platform itself
