### ISSUE TITLE
api/token_config.py module mentioned in API tutorials cant be found

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/academy#151]
As noted in this [discussion](https://github.com/OpenEnergyPlatform/oeplatform/discussions/930), the [token_config.py](https://github.com/OpenEnergyPlatform/tutorial/blob/develop/api/token_config.py) module cannot be found via the tutorials on the OEP website. The module is located in the tutorials repo and is mainly used in the[ API tutorials](https://openenergy-platform.org/tutorials/jupyter/OEP_API_tutorial_part1/#0.-Setup-token) to guide the user in entering the OEP API token. 
The API tutorials should link to this module so that it is understandable how the user can use it.

**Comment by han-f** [comment]
@wingechr @jh-RLI  can we close this, or does this need changes to the API tutorials?

**Comment by han-f** [comment]
@wingechr - can this be closed?

**Comment by jh-RLI** [comment]
I think we do not use the token config module anymore.

**Comment by wingechr** [comment]
yes, this is no longer mentioned in the tutorials
