### ISSUE TITLE
Update example metadata to latest OEMetadata version

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/academy#154]
While reviewing the tutorial files I came across some outdated metadata (mostly v1.4.0). We should update these files to oem v1.5.1 files and also update the tutorials if needed.

**Comment by steull** [comment]
Next week, I will update all metadata to v1.5.1. After that, we can also update the tutorials

**Comment by han-f** [comment]
Closing this issue, as we now have the metadata course (still to update though) https://openenergyplatform.github.io/academy/courses/07_metadata/#what-other-tools-to-work-with-oemetadata-are-there and a tutorial here: https://openenergyplatform.github.io/academy/tutorials/99_other/getting_started_with_OEMetadata/

where I do not see outdated metadata within the tutorials.
