### ISSUE TITLE
Feedback on Beginners Guide

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/academy#159]
## Tutorial / CBM

Tutorial: Beginners Guide
https://openenergy-platform.org/tutorials/11/
Part 1.1 and Part 1.2

[02 - How to get started with the Open Energy Family and Platform](https://openenergy-platform.org/tutorials/)

## Goals

- Create accounts (OEP/GitHub)
- Login
- Setup User Account
- Join Groups
- Start interaction

**Comment by Ludee** [comment]
# Registration Bug

## Description of the issue

Using the same email twice returns a meltdown.

## Steps to Reproduce
1. Register with an email
2. Register another name with the same email

Error message:

> IntegrityError at /user/activate/
duplicate key value violates unique constraint "login_myuser_mail_address_key"
DETAIL:  Key (email)=(XXX@YYY) already exists.

## Ideas of solution

Return a warning and inform user.

## Context and Environment
* Version used: v0.11.1
* Operating system: Windows
* Environment setup and (python) version: Chrome and Firefox

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)

**Comment by han-f** [comment]
any update here? @marlaschallon did you have a chance to try this?

**Comment by marlaschallon** [comment]
> any update here? @marlaschallon did you have a chance to try this?

i almost finished going through the beginners course, but now i doesn´t seem to open anymore: "404 There isn't a GitHub Pages site here."

**Comment by han-f** [comment]
Thats right, we have moved the courses. You can find it here now: https://openenergyplatform.github.io/academy/tutorials/upload/11_beginners_guide/

**Comment by han-f** [comment]
@marlaschallon - any chance we will receive feedback?

**Comment by han-f** [comment]
Closing this issue as still link to legacy and we have a separate issue for the course
