### ISSUE TITLE
Trainings Metainfo: style smaller

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/academy#161]
It would be great if the metainfo for training courses could look different to the main text.
I think if the text would be smaller and grey with less spacing between the lines, this would be a nice "metadata" indicator which makes it stand out from the main body of the text. 

![grafik](https://user-images.githubusercontent.com/36844029/225265454-e6500907-4355-476b-bba4-431d10029607.png)

**Comment by wingechr** [comment]
Everything after "About this course" heading will be small
